# This workflow applies labels to pull requests based on the paths that are
# modified in the pull request.
#
# Edit `.github/labeler.yml` to configure labels. For more information, see
# https://github.com/actions/labeler.

name: Pull Request Labeler
permissions: read-all

on:
  pull_request_target

jobs:
  label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@bee50fefe18762fad67754b2f3bfff2c8082ebb8
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
